/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardGuestRouteRouteImport } from './routes/dashboard/_guest/route'
import { Route as DashboardAuthRouteRouteImport } from './routes/dashboard/_auth/route'
import { Route as DashboardGuestSignUpRouteImport } from './routes/dashboard/_guest/sign-up'
import { Route as DashboardGuestSignInRouteImport } from './routes/dashboard/_guest/sign-in'
import { Route as DashboardGuestResetPasswordRouteImport } from './routes/dashboard/_guest/reset-password'
import { Route as DashboardGuestForgotPasswordRouteImport } from './routes/dashboard/_guest/forgot-password'
import { Route as DashboardAuthSettingsRouteImport } from './routes/dashboard/_auth/settings'
import { Route as DashboardAuthOverviewRouteImport } from './routes/dashboard/_auth/overview'
import { Route as DashboardAuthClicksRouteImport } from './routes/dashboard/_auth/clicks'
import { Route as DashboardAuthBillingRouteImport } from './routes/dashboard/_auth/billing'
import { Route as DashboardAuthAnalyticsRouteImport } from './routes/dashboard/_auth/analytics'
import { Route as DashboardAuthLinksIndexRouteImport } from './routes/dashboard/_auth/links/index'
import { Route as DashboardAuthLinksIdRouteImport } from './routes/dashboard/_auth/links/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGuestRouteRoute = DashboardGuestRouteRouteImport.update({
  id: '/dashboard/_guest',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAuthRouteRoute = DashboardAuthRouteRouteImport.update({
  id: '/dashboard/_auth',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGuestSignUpRoute = DashboardGuestSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => DashboardGuestRouteRoute,
} as any)
const DashboardGuestSignInRoute = DashboardGuestSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => DashboardGuestRouteRoute,
} as any)
const DashboardGuestResetPasswordRoute =
  DashboardGuestResetPasswordRouteImport.update({
    id: '/reset-password',
    path: '/reset-password',
    getParentRoute: () => DashboardGuestRouteRoute,
  } as any)
const DashboardGuestForgotPasswordRoute =
  DashboardGuestForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => DashboardGuestRouteRoute,
  } as any)
const DashboardAuthSettingsRoute = DashboardAuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardAuthRouteRoute,
} as any)
const DashboardAuthOverviewRoute = DashboardAuthOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DashboardAuthRouteRoute,
} as any)
const DashboardAuthClicksRoute = DashboardAuthClicksRouteImport.update({
  id: '/clicks',
  path: '/clicks',
  getParentRoute: () => DashboardAuthRouteRoute,
} as any)
const DashboardAuthBillingRoute = DashboardAuthBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardAuthRouteRoute,
} as any)
const DashboardAuthAnalyticsRoute = DashboardAuthAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardAuthRouteRoute,
} as any)
const DashboardAuthLinksIndexRoute = DashboardAuthLinksIndexRouteImport.update({
  id: '/links/',
  path: '/links/',
  getParentRoute: () => DashboardAuthRouteRoute,
} as any)
const DashboardAuthLinksIdRoute = DashboardAuthLinksIdRouteImport.update({
  id: '/links/$id',
  path: '/links/$id',
  getParentRoute: () => DashboardAuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardGuestRouteRouteWithChildren
  '/dashboard/analytics': typeof DashboardAuthAnalyticsRoute
  '/dashboard/billing': typeof DashboardAuthBillingRoute
  '/dashboard/clicks': typeof DashboardAuthClicksRoute
  '/dashboard/overview': typeof DashboardAuthOverviewRoute
  '/dashboard/settings': typeof DashboardAuthSettingsRoute
  '/dashboard/forgot-password': typeof DashboardGuestForgotPasswordRoute
  '/dashboard/reset-password': typeof DashboardGuestResetPasswordRoute
  '/dashboard/sign-in': typeof DashboardGuestSignInRoute
  '/dashboard/sign-up': typeof DashboardGuestSignUpRoute
  '/dashboard/links/$id': typeof DashboardAuthLinksIdRoute
  '/dashboard/links/': typeof DashboardAuthLinksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardGuestRouteRouteWithChildren
  '/dashboard/analytics': typeof DashboardAuthAnalyticsRoute
  '/dashboard/billing': typeof DashboardAuthBillingRoute
  '/dashboard/clicks': typeof DashboardAuthClicksRoute
  '/dashboard/overview': typeof DashboardAuthOverviewRoute
  '/dashboard/settings': typeof DashboardAuthSettingsRoute
  '/dashboard/forgot-password': typeof DashboardGuestForgotPasswordRoute
  '/dashboard/reset-password': typeof DashboardGuestResetPasswordRoute
  '/dashboard/sign-in': typeof DashboardGuestSignInRoute
  '/dashboard/sign-up': typeof DashboardGuestSignUpRoute
  '/dashboard/links/$id': typeof DashboardAuthLinksIdRoute
  '/dashboard/links': typeof DashboardAuthLinksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard/_auth': typeof DashboardAuthRouteRouteWithChildren
  '/dashboard/_guest': typeof DashboardGuestRouteRouteWithChildren
  '/dashboard/_auth/analytics': typeof DashboardAuthAnalyticsRoute
  '/dashboard/_auth/billing': typeof DashboardAuthBillingRoute
  '/dashboard/_auth/clicks': typeof DashboardAuthClicksRoute
  '/dashboard/_auth/overview': typeof DashboardAuthOverviewRoute
  '/dashboard/_auth/settings': typeof DashboardAuthSettingsRoute
  '/dashboard/_guest/forgot-password': typeof DashboardGuestForgotPasswordRoute
  '/dashboard/_guest/reset-password': typeof DashboardGuestResetPasswordRoute
  '/dashboard/_guest/sign-in': typeof DashboardGuestSignInRoute
  '/dashboard/_guest/sign-up': typeof DashboardGuestSignUpRoute
  '/dashboard/_auth/links/$id': typeof DashboardAuthLinksIdRoute
  '/dashboard/_auth/links/': typeof DashboardAuthLinksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/analytics'
    | '/dashboard/billing'
    | '/dashboard/clicks'
    | '/dashboard/overview'
    | '/dashboard/settings'
    | '/dashboard/forgot-password'
    | '/dashboard/reset-password'
    | '/dashboard/sign-in'
    | '/dashboard/sign-up'
    | '/dashboard/links/$id'
    | '/dashboard/links/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/analytics'
    | '/dashboard/billing'
    | '/dashboard/clicks'
    | '/dashboard/overview'
    | '/dashboard/settings'
    | '/dashboard/forgot-password'
    | '/dashboard/reset-password'
    | '/dashboard/sign-in'
    | '/dashboard/sign-up'
    | '/dashboard/links/$id'
    | '/dashboard/links'
  id:
    | '__root__'
    | '/'
    | '/dashboard/_auth'
    | '/dashboard/_guest'
    | '/dashboard/_auth/analytics'
    | '/dashboard/_auth/billing'
    | '/dashboard/_auth/clicks'
    | '/dashboard/_auth/overview'
    | '/dashboard/_auth/settings'
    | '/dashboard/_guest/forgot-password'
    | '/dashboard/_guest/reset-password'
    | '/dashboard/_guest/sign-in'
    | '/dashboard/_guest/sign-up'
    | '/dashboard/_auth/links/$id'
    | '/dashboard/_auth/links/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardAuthRouteRoute: typeof DashboardAuthRouteRouteWithChildren
  DashboardGuestRouteRoute: typeof DashboardGuestRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_guest': {
      id: '/dashboard/_guest'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardGuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_auth': {
      id: '/dashboard/_auth'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardAuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_guest/sign-up': {
      id: '/dashboard/_guest/sign-up'
      path: '/sign-up'
      fullPath: '/dashboard/sign-up'
      preLoaderRoute: typeof DashboardGuestSignUpRouteImport
      parentRoute: typeof DashboardGuestRouteRoute
    }
    '/dashboard/_guest/sign-in': {
      id: '/dashboard/_guest/sign-in'
      path: '/sign-in'
      fullPath: '/dashboard/sign-in'
      preLoaderRoute: typeof DashboardGuestSignInRouteImport
      parentRoute: typeof DashboardGuestRouteRoute
    }
    '/dashboard/_guest/reset-password': {
      id: '/dashboard/_guest/reset-password'
      path: '/reset-password'
      fullPath: '/dashboard/reset-password'
      preLoaderRoute: typeof DashboardGuestResetPasswordRouteImport
      parentRoute: typeof DashboardGuestRouteRoute
    }
    '/dashboard/_guest/forgot-password': {
      id: '/dashboard/_guest/forgot-password'
      path: '/forgot-password'
      fullPath: '/dashboard/forgot-password'
      preLoaderRoute: typeof DashboardGuestForgotPasswordRouteImport
      parentRoute: typeof DashboardGuestRouteRoute
    }
    '/dashboard/_auth/settings': {
      id: '/dashboard/_auth/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardAuthSettingsRouteImport
      parentRoute: typeof DashboardAuthRouteRoute
    }
    '/dashboard/_auth/overview': {
      id: '/dashboard/_auth/overview'
      path: '/overview'
      fullPath: '/dashboard/overview'
      preLoaderRoute: typeof DashboardAuthOverviewRouteImport
      parentRoute: typeof DashboardAuthRouteRoute
    }
    '/dashboard/_auth/clicks': {
      id: '/dashboard/_auth/clicks'
      path: '/clicks'
      fullPath: '/dashboard/clicks'
      preLoaderRoute: typeof DashboardAuthClicksRouteImport
      parentRoute: typeof DashboardAuthRouteRoute
    }
    '/dashboard/_auth/billing': {
      id: '/dashboard/_auth/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardAuthBillingRouteImport
      parentRoute: typeof DashboardAuthRouteRoute
    }
    '/dashboard/_auth/analytics': {
      id: '/dashboard/_auth/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAuthAnalyticsRouteImport
      parentRoute: typeof DashboardAuthRouteRoute
    }
    '/dashboard/_auth/links/': {
      id: '/dashboard/_auth/links/'
      path: '/links'
      fullPath: '/dashboard/links/'
      preLoaderRoute: typeof DashboardAuthLinksIndexRouteImport
      parentRoute: typeof DashboardAuthRouteRoute
    }
    '/dashboard/_auth/links/$id': {
      id: '/dashboard/_auth/links/$id'
      path: '/links/$id'
      fullPath: '/dashboard/links/$id'
      preLoaderRoute: typeof DashboardAuthLinksIdRouteImport
      parentRoute: typeof DashboardAuthRouteRoute
    }
  }
}

interface DashboardAuthRouteRouteChildren {
  DashboardAuthAnalyticsRoute: typeof DashboardAuthAnalyticsRoute
  DashboardAuthBillingRoute: typeof DashboardAuthBillingRoute
  DashboardAuthClicksRoute: typeof DashboardAuthClicksRoute
  DashboardAuthOverviewRoute: typeof DashboardAuthOverviewRoute
  DashboardAuthSettingsRoute: typeof DashboardAuthSettingsRoute
  DashboardAuthLinksIdRoute: typeof DashboardAuthLinksIdRoute
  DashboardAuthLinksIndexRoute: typeof DashboardAuthLinksIndexRoute
}

const DashboardAuthRouteRouteChildren: DashboardAuthRouteRouteChildren = {
  DashboardAuthAnalyticsRoute: DashboardAuthAnalyticsRoute,
  DashboardAuthBillingRoute: DashboardAuthBillingRoute,
  DashboardAuthClicksRoute: DashboardAuthClicksRoute,
  DashboardAuthOverviewRoute: DashboardAuthOverviewRoute,
  DashboardAuthSettingsRoute: DashboardAuthSettingsRoute,
  DashboardAuthLinksIdRoute: DashboardAuthLinksIdRoute,
  DashboardAuthLinksIndexRoute: DashboardAuthLinksIndexRoute,
}

const DashboardAuthRouteRouteWithChildren =
  DashboardAuthRouteRoute._addFileChildren(DashboardAuthRouteRouteChildren)

interface DashboardGuestRouteRouteChildren {
  DashboardGuestForgotPasswordRoute: typeof DashboardGuestForgotPasswordRoute
  DashboardGuestResetPasswordRoute: typeof DashboardGuestResetPasswordRoute
  DashboardGuestSignInRoute: typeof DashboardGuestSignInRoute
  DashboardGuestSignUpRoute: typeof DashboardGuestSignUpRoute
}

const DashboardGuestRouteRouteChildren: DashboardGuestRouteRouteChildren = {
  DashboardGuestForgotPasswordRoute: DashboardGuestForgotPasswordRoute,
  DashboardGuestResetPasswordRoute: DashboardGuestResetPasswordRoute,
  DashboardGuestSignInRoute: DashboardGuestSignInRoute,
  DashboardGuestSignUpRoute: DashboardGuestSignUpRoute,
}

const DashboardGuestRouteRouteWithChildren =
  DashboardGuestRouteRoute._addFileChildren(DashboardGuestRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardAuthRouteRoute: DashboardAuthRouteRouteWithChildren,
  DashboardGuestRouteRoute: DashboardGuestRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
